# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JarvisRegistry < Formula
  desc "Companion CLI for the Jarvis Registry platform."
  homepage "https://github.com/ascending-llc/jarvis-registry-cli"
  version "0.6.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ascending-llc/jarvis-registry-cli/releases/download/v0.6.6/jarvis-registry_0.6.6_darwin_amd64.tar.gz"
      sha256 "b3f2001cdd8425b3152216f23347b02009565267e0d5d137dd737bf4e721a322"

      define_method(:install) do
        bin.install "jarvis-registry"
        bash_completion.install "completions/jarvis-registry.bash" => "jarvis-registry"
        bash_completion.install_symlink "jarvis-registry" => "jr"
        zsh_completion.install "completions/jarvis-registry.zsh" => "_jarvis-registry"
        fish_completion.install "completions/jarvis-registry.fish"
        fish_completion.install "completions/jr.fish"
        bin.install_symlink "jarvis-registry" => "jr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ascending-llc/jarvis-registry-cli/releases/download/v0.6.6/jarvis-registry_0.6.6_darwin_arm64.tar.gz"
      sha256 "7a7325209a44b1816d508f86267c8bbc6c5056ed199ecdfaf48cff7a3e3f6372"

      define_method(:install) do
        bin.install "jarvis-registry"
        bash_completion.install "completions/jarvis-registry.bash" => "jarvis-registry"
        bash_completion.install_symlink "jarvis-registry" => "jr"
        zsh_completion.install "completions/jarvis-registry.zsh" => "_jarvis-registry"
        fish_completion.install "completions/jarvis-registry.fish"
        fish_completion.install "completions/jr.fish"
        bin.install_symlink "jarvis-registry" => "jr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ascending-llc/jarvis-registry-cli/releases/download/v0.6.6/jarvis-registry_0.6.6_linux_amd64.tar.gz"
      sha256 "21b401be44cb510d1f47adb2d0d286ef4c66c7335e36a42930fff451df2c0d19"
      define_method(:install) do
        bin.install "jarvis-registry"
        bash_completion.install "completions/jarvis-registry.bash" => "jarvis-registry"
        bash_completion.install_symlink "jarvis-registry" => "jr"
        zsh_completion.install "completions/jarvis-registry.zsh" => "_jarvis-registry"
        fish_completion.install "completions/jarvis-registry.fish"
        fish_completion.install "completions/jr.fish"
        bin.install_symlink "jarvis-registry" => "jr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ascending-llc/jarvis-registry-cli/releases/download/v0.6.6/jarvis-registry_0.6.6_linux_arm64.tar.gz"
      sha256 "5fadae73d046461604e372bdb6b9bf2212891b001e3c8d987b37abc570330c02"
      define_method(:install) do
        bin.install "jarvis-registry"
        bash_completion.install "completions/jarvis-registry.bash" => "jarvis-registry"
        bash_completion.install_symlink "jarvis-registry" => "jr"
        zsh_completion.install "completions/jarvis-registry.zsh" => "_jarvis-registry"
        fish_completion.install "completions/jarvis-registry.fish"
        fish_completion.install "completions/jr.fish"
        bin.install_symlink "jarvis-registry" => "jr"
      end
    end
  end

  def caveats
    <<~EOS
      Run these once, in order, to get started:
        1. jarvis-registry configure   - set the Registry base URL and skills sync mode
        2. jarvis-registry auth login  - sign in via browser (cached in your OS keyring)
        3. jarvis-registry skills sync - pull the skills you have access to

      Run `jarvis-registry --help` for the full flag reference.

      A `jr` symlink has also been installed as a shorthand for `jarvis-registry`.
    EOS
  end

  test do
    system "#{bin}/jarvis-registry", "--version"
    system "#{bin}/jarvis-registry", "-v"
  end
end
